### PR TITLE
Update creatures_gui_fr.properties

### PR DESCRIPTION
**Pull request by Berzetoberze**

### CODE REVIEW

**Comment by Hokan-Ashir** [comment]
Wouldn't it be easier and shorter to rename
"Seulement les emplacements des anneaux et des armes/boucliers est disponible"
to
"Emplacements des anneaux et des armes"
?

Cause such slot requirement and description already says that hero only has hands and ring's slots available, no need to specify shields and use "suelement"

Also, about "Probabilité d'obtenir un objet" phrase, don't we just need to describe that **item** can be dropped and not Avatar can obtain/get access to item?

**Comment by Berzetoberze** [comment]
I have translate for to be the more clearly as possible! But if you need a short translation you can put this:
Emplacements des anneaux, armes et boucliers disponibles

For the "Probabilité d'obtenir un objet" in french we don't have good translation for "drop" soo I have put this because it's the more adapted.

**Comment by Hokan-Ashir** [comment]
> Emplacements des anneaux, armes et boucliers disponibles

Yeah, I really fear, that such long string won't have nice look into GUI. And by the way, don't we already state in "Emplacements des anneaux et des armes" sentence that only hands slots are available?

> For the "Probabilité d'obtenir un objet" in french we don't have good translation for "drop" soo I have put this because it's the more adapted.

Okay, I got you. Not an expert in French, just learning, so don't know nuances =)
I'll merge request(s) sooner

**Comment by Berzetoberze** [comment]
For the "Only hands slots are available" we can't translate that with "Seulement l'emplacement des mains disponibles" it's kind wierd... soo I have propose this "Seulement l'emplacement des anneaux, armes et boucliers est disponible" it's a bit long. I know but I don't know, how make it shorter.

**Comment by Hokan-Ashir** [comment]
Well, I left "Emplacements des anneaux et des armes" and merged source
Maybe you're searching for perfection, but one misleading localization won't ruin the day =)

**Comment by Berzetoberze** [comment]
Touché... ^^'

**Pull request merged**
